# Generated by Django 4.2.7 on 2023-11-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='accounts',
            new_name='user',
        ),
    ]
