# Generated by Django 4.2.7 on 2023-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_accounts_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
