# Generated by Django 4.2.7 on 2023-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='bielgomes', max_length=50),
            preserve_default=False,
        ),
    ]
